#!/bin/bash
# Copyright 2012 Google Inc.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Usage:
#
# tools/generate_build_info
#     Emits a JavaScript variable definition for cm_build_info with details
#     about the current build.  Used by Makefile rules to make build_info.js.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

build=$(pwd)
version="$(hg id 2>/dev/null || echo unknown)"  # for now, assumes Mercurial

cat <<EOF
window = (typeof window === 'undefined') ? {} : window;
window['cm_build_info'] = {
  "release": false,
  "version": "$version",
  "user": "$(whoami)",
  "path": "$APP_DIR"
};
EOF
