#!/bin/bash
# Copyright 2012 Google Inc.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Usage:
#
# tools/pytests
#     Runs the Python unit tests.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

# Remove old .pyc files to ensure that we are using Python 2.7 for tests.
find . -name '*.pyc' -exec rm -f {} ';'

if py.test-2.7 --version 2>/dev/null; then
    # Use py.test if it's available (it's faster and produces a nicer report).
    if [ -n "$1" ]; then
        py.test-2.7 --tb=short "$@"
    else
        py.test-2.7 --tb=short *_test.py
    fi
else
    # Otherwise, just execute the tests one by one.
    for i in *_test.py; do
        echo
        echo ==== $i:
        python2.7 $i
    done
fi
