#!/bin/bash
# Copyright 2012 Google Inc.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Usage:
#
# tools/python [arguments]
#     Launches the Python interpreter with the PYTHONPATH and other
#     environment variables set up as for running the dev server.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

echo PYTHONPATH="$PYTHONPATH"
echo $PYTHON "$@"
$PYTHON "$@"
